# theme
[general]
import = [
    "~/.config/alacritty/gruvbox.toml"
]

# fonts
[font]
size = 12.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
style = "Bold"

[font.italic]
style = "Italic"

[cursor]
style = { shape = "Beam", blinking = "Off" }
# vi_mode_style = { shape = "Beam", thickness = 0.25 }


